"""Ontario province profile."""

from canada_id.provinces.base import (
    CAN_AAMVA_VERSION,
    CAN_CARD_HEIGHT,
    CAN_CARD_WIDTH,
    CAN_COUNTRY,
    CAN_DATE_FORMAT,
    CAN_HEIGHT_UNIT,
    CAN_OPTIONAL_FIELDS,
    CAN_POSTAL_PATTERN,
    CAN_REQUIRED_FIELDS,
    ProvinceProfile,
)

PROFILE = ProvinceProfile(
    code="ON",
    name="Ontario",
    iin="636012",
    country=CAN_COUNTRY,
    aamva_version=CAN_AAMVA_VERSION,
    date_format=CAN_DATE_FORMAT,
    height_unit=CAN_HEIGHT_UNIT,
    postal_code_pattern=CAN_POSTAL_PATTERN,
    required_fields=CAN_REQUIRED_FIELDS,
    optional_fields=CAN_OPTIONAL_FIELDS,
    vehicle_classes={
        "G": "Car, light truck (full privilege)",
        "G1": "Car, light truck (learner)",
        "G2": "Car, light truck (novice)",
        "M": "Motorcycle (full privilege)",
        "M1": "Motorcycle (learner)",
        "M2": "Motorcycle (novice/limited speed)",
        "A": "Tractor-trailer combination",
        "B": "School bus",
        "C": "Bus (regular route urban transit)",
        "D": "Truck over 11,000 kg or bus (more than 24 pax)",
        "E": "School bus (max 24 pax) or ambulance",
        "F": "Regular bus (max 24 pax) or ambulance",
    },
    restriction_codes={
        "A": "Corrective lenses",
        "B": "Outside mirrors",
        "C": "Daylight driving only",
        "D": "Speed limited",
        "E": "Automatic transmission",
        "F": "Hand controls",
        "G": "Interlock device",
        "H": "Hearing aid",
        "J": "Left-foot accelerator",
    },
    endorsement_codes={
        "S": "School bus",
        "A": "Air brakes",
        "Z": "Air brakes (Z endorsement)",
    },
    card_width_mm=CAN_CARD_WIDTH,
    card_height_mm=CAN_CARD_HEIGHT,
    jurisdiction_version=5,
)
